### ISSUE TITLE
Include python package manager

### ISSUE THREAD

**Issue by rkrishnasanka** [Agriworks/agriworks_platform#2]
I think the repo will be more maintainable and easier for development if venv /pipenv for the project:

Links:
- https://realpython.com/python-virtual-environments-a-primer/
- https://pipenv-fork.readthedocs.io/en/latest/

I'm not sure if there are newer/better package managers but this'll be good to reduce the number of errors and simplify the installation requirements.

**Comment by mdesilva** [comment]
package manager pip and virtual env have been used from the start. See readme for instructions on how to setup your environment for local development.
