### ISSUE TITLE
POST function of API ambiguous

### ISSUE THREAD

**Issue by rkrishnasanka** [Agriworks/agriworks_platform#9]
This method works with both the `GET` and `POST` methods. REST API should not be ambiguous, each of the HTTP methods should have unique operations for a given url path.

https://github.com/Hack4Impact-Boston-University/agriworks_platform/blob/dd1cef076cf8357b156f863c986e1da55e750843/Controllers/DownloadController.py#L40

**Comment by mdesilva** [comment]
method no longer exists, and all routes now serve a single method as appropriate
